// import styles from "@/styles/Home.module.css";

import HomePage from "@/components/elements/HomaPage";
import verifyTableNumber from "@/helper/verifyTableNumber";
import { SAVETABLENUMBER } from "@/redux/features/ReduxCart";
import { useSearchParams } from "next/navigation";
import { useEffect } from "react";
import { useDispatch } from "react-redux";

export default function Home() {
    const dispatch = useDispatch();
    // save number table in redux-persist
    const searchParams = useSearchParams();
    const tableNumber = searchParams.get("table");
    const res = verifyTableNumber(tableNumber);

    useEffect(() => {
        if (res) {
            dispatch(SAVETABLENUMBER(res));
        } else {
            dispatch(SAVETABLENUMBER(res));
        }
    }, []);
    return <HomePage />;
}

{
    /* <Head>
import Head from "next/head";

                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head> */
}
